### ISSUE TITLE
Show actual block height instead of topo height

### ISSUE THREAD

**Issue by tripflex** [xelis-project/xelis-explorer-legacy#1]
In the header/title you're showing the topo height which can be confusing for some, as we all know that value can change dynamically.  

Would be good to instead show the actual block height (especially if already past stable height)

https://github.com/xelis-project/xelis-explorer/blob/master/src/pages/block/index.js
<img width="777" alt="image" src="https://github.com/xelis-project/xelis-explorer/assets/553732/eada0b97-2bc1-465b-9ae8-bb1bd70633b1">

**Comment by g45t345rt** [comment]
The block title is now showing the `hash` instead of the `topoheight`. 
I know it's not what you were asking, but the block `height` is not unique and can't be referenced as a single block page.
I have opted to create a new page `/height/:height` to show blocks at a specific height.

For example, you can view blocks by using:
- Topo: https://explorer.xelis.io/blocks/216803
- Hash: https://explorer.xelis.io/blocks/9c03594f61b3c08047479a7bf99939a1d3141e0aee8c870c2f22451fbbe7a525
- Height: https://explorer.xelis.io/height/204970

I hope this can help others to navigate around the confusion of height and topoheight reorg.
